version: "3"
services:
  authentication-server:
    build: .
    ports:
      - "3003:3003"
    environment:
      - DBHOST=users-database
  users-database:
    image: mongo
    ports:
      - "27017:27017"
